### ISSUE TITLE
why go get -u github.com/robaho/fixed ERROR

### ISSUE THREAD

**Issue by lxingh** [robaho/fixed#19]
```
> go get -u -v github.com/robaho/fixed
github.com/robaho/fixed (download)
github.com/robaho/fixed
# github.com/robaho/fixed
D:\MyProgram\Go\src\github.com\robaho\fixed\decomposer.go:62:19: invalid operation: uint64(v) << (i * 8) (shift count type int, must be unsigned integer)
```

**Comment by robaho** [comment]
@kardianos your PR you submitted didn't even compile - I just assumed it did since it included a test case. I find it hard to believe you didn't test, so not sure how this came to be.

Anyway I fixed the code and committed, but we should figure out what happened.

@lxingh it should work for you now if you pull the latest

**Comment by lxingh** [comment]
now is work,Thinks!!!

**Comment by kardianos** [comment]
It's possible I was running tip, which allows unsigned shift.

**Comment by robaho** [comment]
@kardianos that is probably not something that you should be doing for these sort of PRs - that being said, I probably should of run the code prior to accepting... :)

**Comment by kardianos** [comment]
Fair. I don't normally use shifts, wasn't top of mind. Sorry for the breakage.
