### ISSUE TITLE
JSON encoding of NaN

### ISSUE THREAD

**Issue by vurguuz** [robaho/fixed#21]
JSON encoding of NaN numbers doesn't work:

func (f Fixed) MarshalJSON() ([]byte, error) {
	buffer := make([]byte, 24)
	return itoa(buffer, f.fp), nil
}

**Comment by robaho** [comment]
JSON does not support NaN values.

**Comment by robaho** [comment]
See json.org - the only viable option would be to encode as null or as strings.

**Comment by robaho** [comment]
it seems the Go JSON decoder will support encoding/decoding the NaN - it will be a string value in this case. It probably won't work in a standards sense, but it works within Go

since the old way was not cross platform anyway - since JSON does not support NaN, and it would have been rendered as a really large number, changing this is ok
